import polib

po = polib.pofile('locale/en/LC_MESSAGES/django.po')

translations = {
    "لوحة تحكم الهلال الدولي": "Alhilal International Dashboard",
    "الهلال الدولي": "Alhilal International",
    "إدارة الموقع": "Site Administration",
    "لوحة التحكم": "Dashboard",
    "الرئيسية": "Dashboard",  # In dashboard context
    "المواشي": "Livestock",
    "التصنيفات": "Categories",
    "الأخبار": "News",
    "الرسائل": "Messages",
    "صور الغلاف": "Hero Images",
    "الإعدادات": "Settings",
    "عرض الموقع": "View Site",
    "البحث في لوحة التحكم...": "Search dashboard...",
    "إدارة التصنيفات": "Category Management",
    "تصنيفات المواشي": "Livestock Categories",
    "إضافة تصنيف": "Add Category",
    "الأيقونة": "Icon",
    "الاسم (Ar)": "Name (Ar)",
    "الاسم (En)": "Name (En)",
    "الترتيب": "Order",
    "الإجراءات": "Actions",
    "لا توجد تصنيفات مضافة": "No categories added",
    "تعديل التصنيف:": "Edit Category:",
    "إضافة تصنيف جديد": "Add New Category",
    "تعديل": "Edit",
    "إضافة": "Add",
    "حفظ": "Save",
    "إلغاء": "Cancel",
    "تأكيد الحذف": "Confirm Delete",
    "هل أنت متأكد؟": "Are you sure?",
    "أنت على وشك حذف:": "You are about to delete:",
    "هذا الإجراء لا يمكن التراجع عنه.": "This action cannot be undone.",
    "حذف نهائي": "Delete Permanently",
    "تعديل صورة الغلاف:": "Edit Hero Image:",
    "إضافة صورة غلاف جديدة": "Add New Hero Image",
    "حفظ التغييرات": "Save Changes",
    "إدارة صور الغلاف (Hero)": "Hero Images Management",
    "قائمة الصور": "Images List",
    "إضافة صورة جديدة": "Add New Image",
    "الصورة": "Image",
    "العنوان (Ar)": "Title (Ar)",
    "الحالة": "Status",
    "نشط": "Active",
    "غير نشط": "Inactive",
    "لا توجد صور غلاف مضافة": "No hero images added",
    "إجمالي المواشي": "Total Livestock",
    "الأخبار المنشورة": "Published News",
    "رسائل جديدة": "New Messages",
    "إجمالي الرسائل": "Total Messages",
    "إجراءات سريعة": "Quick Actions",
    "إضافة مواشي": "Add Livestock",
    "نشر مقال": "Post Article",
    "تحديث الغلاف": "Update Hero",
    "نشاط الموقع": "Site Activity",
    "آخر الرسائل": "Recent Messages",
    "عرض الكل": "View All",
    "الاسم": "Name",
    "الموضوع": "Subject",
    "مقروءة": "Read",
    "جديدة": "New",
    "لا توجد رسائل بعد": "No messages yet",
    "آخر الأخبار": "Recent News",
    "العنوان": "Title",
    "منشور": "Published",
    "مسودة": "Draft",
    "لا توجد أخبار بعد": "No news yet",
    "الزيارات": "Visits",
    "تعديل:": "Edit:",
    "إضافة مواشي جديدة": "Add New Livestock",
    "إدارة المواشي": "Livestock Management",
    "قائمة المواشي": "Livestock List",
    "إضافة جديد": "Add New",
    "التصنيف": "Category",
    "تاريخ الإضافة": "Date Added",
    "لا توجد مواشي مضافة": "No livestock added",
    "تفاصيل الرسالة": "Message Details",
    "عرض": "View",
    "الاسم الكامل": "Full Name",
    "البريد الإلكتروني": "Email",
    "رقم الهاتف": "Phone Number",
    "نص الرسالة": "Message Body",
    "تاريخ الإرسال": "Sent Date",
    "العودة للقائمة": "Back to List",
    "رد عبر البريد": "Reply via Email",
    "رسائل التواصل": "Contact Messages",
    "الرسائل الواردة": "Incoming Messages",
    "التاريخ": "Date",
    "لا توجد رسائل واردة": "No incoming messages",
    "تعديل المقال:": "Edit Article:",
    "إضافة مقال جديد": "Add New Article",
    "نشر المقال": "Publish Article",
    "إدارة الأخبار": "News Management",
    "قائمة المقالات": "Articles List",
    "إضافة مقال": "Add Article",
    "تاريخ النشر": "Published Date",
    "لا توجد أخبار مضافة": "No news added",
    "نتائج البحث": "Search Results",
    "البحث": "Search",
    "نتائج البحث عن:": "Search results for:",
    "لم يتم العثور على أي نتائج مطابقة.": "No matching results found.",
    "إعدادات الموقع": "Site Settings",
    "حفظ الإعدادات": "Save Settings",
    "رقم الهاتف": "Phone Number",
    "العنوان (En)": "Title (En)",
    "Slug": "Slug",
    "Order": "Order",
    "Name (En)": "Name (En)"
}

count = 0
for entry in po:
    if entry.msgid in translations and not entry.msgstr:
        entry.msgstr = translations[entry.msgid]
        count += 1
        
po.save()
print(f"Translated {count} entries.")
