# Generated by Django 4.2.24 on 2026-01-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Is Read")),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="Title (Ar)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (En)"),
                ),
                ("subtitle_ar", models.TextField(verbose_name="Subtitle (Ar)")),
                ("subtitle_en", models.TextField(verbose_name="Subtitle (En)")),
                (
                    "image",
                    models.ImageField(
                        upload_to="hero/", verbose_name="Background Image"
                    ),
                ),
                (
                    "cta_text_ar",
                    models.CharField(max_length=50, verbose_name="CTA Text (Ar)"),
                ),
                (
                    "cta_text_en",
                    models.CharField(max_length=50, verbose_name="CTA Text (En)"),
                ),
                (
                    "cta_link",
                    models.CharField(
                        default="#", max_length=200, verbose_name="CTA Link"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="settings/", verbose_name="Logo")),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="settings/",
                        verbose_name="Favicon",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("address_ar", models.TextField(verbose_name="Address (Ar)")),
                ("address_en", models.TextField(verbose_name="Address (En)")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("twitter", models.URLField(blank=True, verbose_name="Twitter")),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
