# Generated by Django 4.2.24 on 2026-01-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="google_maps_embed",
            field=models.TextField(
                blank=True,
                help_text="Paste your Google Maps iframe code here",
                verbose_name="Google Maps Embed Code",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="phone_whatsapp",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="WhatsApp Phone"
            ),
        ),
    ]
