# Generated by Django 4.2.24 on 2026-01-24 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ar", models.CharField(max_length=100, verbose_name="Name (Ar)")),
                ("name_en", models.CharField(max_length=100, verbose_name="Name (En)")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="Description (Ar)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (En)"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Icon",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LivestockItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(max_length=200, verbose_name="Title (Ar)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, verbose_name="Title (En)"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("description_ar", models.TextField(verbose_name="Description (Ar)")),
                ("description_en", models.TextField(verbose_name="Description (En)")),
                (
                    "featured_image",
                    models.ImageField(
                        upload_to="livestock/", verbose_name="Featured Image"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Is Featured"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="livestock.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livestock Item",
                "verbose_name_plural": "Livestock Items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaGalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                        verbose_name="Media Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="livestock_gallery/", verbose_name="File"
                    ),
                ),
                (
                    "caption_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption (Ar)"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption (En)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "livestock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="livestock.livestockitem",
                        verbose_name="Livestock Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery Item",
                "verbose_name_plural": "Gallery Items",
                "ordering": ["order"],
            },
        ),
    ]
