# Generated by Django 4.2.24 on 2026-02-06 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("livestock", "0002_category_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                        verbose_name="Media Type",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="category_media/", verbose_name="File"),
                ),
                (
                    "caption_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption (Ar)"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption (En)"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="livestock.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Media",
                "verbose_name_plural": "Category Media Items",
                "ordering": ["order"],
            },
        ),
    ]
