# Generated by Django 4.2.24 on 2026-02-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestock", "0003_categorymedia"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymedia",
            name="mute_video",
            field=models.BooleanField(
                default=True,
                help_text="Mute video audio permanently to reduce size and auto-play quietly.",
                verbose_name="Mute Video",
            ),
        ),
        migrations.AddField(
            model_name="mediagalleryitem",
            name="mute_video",
            field=models.BooleanField(
                default=True,
                help_text="Mute video audio permanently to reduce size and auto-play quietly.",
                verbose_name="Mute Video",
            ),
        ),
    ]
